ongr_translations_list_page:
    pattern: /list
    methods: [GET]
    defaults:
        _controller: ongr_translations.controller.list:listAction

ongr_translations_api_edit:
    pattern: /_api/edit
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:edit
    options:
        expose: true
            
ongr_translations_api_delete:
    pattern: /_api/delete
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:delete
    options:
        expose: true

ongr_translations_api_add:
    pattern: /_api/add
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:add
    options:
        expose: true

ongr_translations_api_get:
    pattern: /_api/get
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:get
    options:
        expose: true

ongr_translations_api_check:
    pattern: /_api/check
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:check
    options:
        expose: true

ongr_translations_api_export:
    pattern: /_api/export
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:export
    options:
        expose: true

ongr_translations_api_history:
    pattern: /_api/history
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:history
    options:
        expose: true
