ongr_translations_list_page:
    pattern: /list
    methods: [GET]
    defaults:
        _controller: ONGRTranslationsBundle:List:list

ongr_translations_translation_edit:
    pattern: /_api/edit/{id}
    methods: [POST]
    defaults:
        _controller: ongr_translations.controller.rest:editAction
    options:
            expose: true
