language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - SYMFONY="2.6.*"
install:
  - composer require --no-update symfony/symfony:${SYMFONY}
script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/ONGR --ignore=vendor,Tests/app ./
before_script:
  - composer self-update
  - composer update --prefer-source
